### ISSUE TITLE
Extract XMP image-data in Safari 14  in a web build flutter project

### ISSUE THREAD

**Issue by lfbrunke** [justkawal/xmp#1] opened 2021-01-18 18:47 UTC
Only Safari error: 

[Log] XMP-data error: FormatException: Illegal RegExp pattern (SyntaxError: Invalid regular expression: invalid group specifier name) (main.dart.js, line 4373)
((?<=[a-z])[0-9])|((?<=[0-9])[a-z])|((?<=[A-Z])[0-9])|((?<=[0-9])[A-Z])|((?...

Work nice in other browsers.

**Comment by justkawal** [comment] 2021-01-19 09:11
@lfbrunke, Hey Lars Brunke
I am unable to reproduce the error, It would be helpful to get the sample picture with you were having issue.

You can mail me the sample picture on contact@kawal.dev

**Comment by justkawal** [comment] 2021-01-30 16:43
@lfbrunke Hey, Sorry for delays, Actually admitted in hospital due to Covid-19.

Will push the change whenever I'll reach home.

Please Stay Healthy and Stay Safe.

Regularly wash your hands.

Thanks 
Long Live 🔥pen Source

**Comment by lfbrunke** [comment] 2021-01-30 16:49
Hi Singh 

Sorry to hear. But hope you are well again.

Best regards
Lars Brunke 
Webstream ApS

Lars Brunke 
Webstream ApS.

**Comment by justkawal** [comment] 2021-02-11 10:30
@lfbrunke 
It's fixed now.
Sorry for delays.

Please reopen the issue if it still persists

**Closed as completed** 2021-02-11 10:29 UTC
Labels: starting to resolve

**Comment by justkawal** [comment] 2021-02-15 13:04
@lfbrunke 
Did it worked on your side ?

**Comment by lfbrunke** [comment] 2021-02-15 13:11
Hi Kawaljeet Singh

Yes it worked. Thanks.

What was the problem. Was it the speciel danish characters?

BR
Lars Brunke

**Comment by justkawal** [comment] 2021-02-15 16:33
@lfbrunke 
Actually, The issue with RegExp was that the safari browsers doesn't support look-back Regular Expression.

So had to use my other package: [utility](https://github.com/justkawal/utility)
